org.gradle.jvmargs=-Xmx2G

# Fabric (https://fabricmc.net/versions.html)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Mod Properties
mod_version=1.21.11_1.2.1.6.1
maven_group=com.nekiplay.neoscripts
archives_base_name=neo-scripts

fabric_version=0.141.2+1.21.11
fabric_kotlin_version=1.13.7+kotlin.2.2.21

## Occlusion Culling (https://github.com/LogisticsCraft/OcclusionCulling)
occlusionculling_version = 0.0.8-SNAPSHOT

## HM API (https://github.com/AzureAaron/hm-api)
hm_api_version=1.0.1+1.21.2

## neu repoparser (https://repo.nea.moe/#/releases/moe/nea/neurepoparser/)
repoparser_version = 1.8.0

## Networth Calculator (https://github.com/AzureAaron/networth-calculator)
networth_calculator_version = 1.0.5

## Legacy Item DFU (https://github.com/AzureAaron/legacy-item-dfu)
legacy_item_dfu_version = 1.0.3+1.21.5

## JGit (https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit)
jgit_version = 7.3.0.202506031305-r

imgui_version=1.90.0
lwjgl_version=3.3.3

## Catboost
catboost_version = 1.2.8
