mod_group=com.nekiplay.neoscripts
mod_id=neoscripts
mod_name=Neo Scripts
mod_authors=Neki_play
mod_version=1.2.1.9.0
mod_description=Lua scripts for Minecraft.
mod_license=LGPLv3

java_version=25

# Fabric (https://fabricmc.net/versions.html)
minecraft_version=26.1.2
fabric_loader_version=0.19.3
fabric_api_version=0.151.0+26.1.2
fabric_kotlin_version=1.13.12+kotlin.2.4.0
## HM API (https://github.com/AzureAaron/hm-api)
hm_api_version=1.0.3+26.1
## neu repoparser (https://repo.nea.moe/#/releases/moe/nea/neurepoparser/)
repoparser_version = 1.10.0
## Networth Calculator (https://github.com/AzureAaron/networth-calculator)
networth_calculator_version = 1.0.5
## Legacy Item DFU (https://github.com/AzureAaron/legacy-item-dfu)
legacy_item_dfu_version = 1.0.3+1.21.5


# NeoForge
neoforge_version=26.1.2.76
mc_versions_neo=[26.1.2]
neo_loader_version_range=*

## JGit (https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit)
jgit_version = 7.3.0.202506031305-r
imgui_version=1.90.0
lwjgl_version=3.3.3
## Catboost
catboost_version = 1.2.8

# Done to improve gradle performance.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
