{
  "formatVersion": "1.1",
  "component": {
    "group": "net.azureaaron",
    "module": "legacy-item-dfu",
    "version": "1.0.3+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "8.0.16"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-item-dfu-1.0.3+1.21.5.jar",
          "url": "legacy-item-dfu-1.0.3+1.21.5.jar",
          "size": 99000,
          "sha512": "4fe5086272350111fe44c284e91de91da08875171bfc0da29fff07315b4b91d8c7b2e1b06962006b78e0adc46e304debfd26803cffad29c9e4933b59920c0f28",
          "sha256": "eb51be08fb08fd4157dcb8c1c78f54159999a33edb6aa599dd049912e02410a1",
          "sha1": "e2540465e5485f675c96edca4a203d23a25c16ed",
          "md5": "6754972c38480deee699e6d121d18a27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "8.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "legacy-item-dfu-1.0.3+1.21.5.jar",
          "url": "legacy-item-dfu-1.0.3+1.21.5.jar",
          "size": 99000,
          "sha512": "4fe5086272350111fe44c284e91de91da08875171bfc0da29fff07315b4b91d8c7b2e1b06962006b78e0adc46e304debfd26803cffad29c9e4933b59920c0f28",
          "sha256": "eb51be08fb08fd4157dcb8c1c78f54159999a33edb6aa599dd049912e02410a1",
          "sha1": "e2540465e5485f675c96edca4a203d23a25c16ed",
          "md5": "6754972c38480deee699e6d121d18a27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "legacy-item-dfu-1.0.3+1.21.5-sources.jar",
          "url": "legacy-item-dfu-1.0.3+1.21.5-sources.jar",
          "size": 41011,
          "sha512": "e4c1851c171134252b34d41cf6e9e755020d4ec524967782bc8c4cef99d7f9a8f39aa16e309258a9980eeea4bf1f98fdfb494653031e10453f44dad4fc8b91c3",
          "sha256": "c2acaed1427eb6a93bbf02473a9daa5bdddd76027819c51dd9320b2a801ebbf3",
          "sha1": "fdc2f4f7a3f0a091efd0b65f601abba89c4c6a00",
          "md5": "421621b130480b607faf01b4e2e5e1b1"
        }
      ]
    }
  ]
}
