{
  "formatVersion": "1.1",
  "component": {
    "group": "net.azureaaron",
    "module": "hm-api",
    "version": "1.0.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hm-api-1.0.1+1.21.2.jar",
          "url": "hm-api-1.0.1+1.21.2.jar",
          "size": 74172,
          "sha512": "c607cdee5613a17f76d58a681dce55b55c87c3e5a521166ae9acca24ba55a81f4e64be91c04a62a7c04006ada8c4f2dabfd0c4a0a506b357e5306618146c4709",
          "sha256": "bd5ad58ffed5ca635c05c67067d42d86050b43ee3554c56248920650fc579e1a",
          "sha1": "ec32366e8fb7ff06fa36181b374be0df64b40020",
          "md5": "11bc674a9f7c8813b3d097e50bec2afe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.106.0+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "hm-api-1.0.1+1.21.2.jar",
          "url": "hm-api-1.0.1+1.21.2.jar",
          "size": 74172,
          "sha512": "c607cdee5613a17f76d58a681dce55b55c87c3e5a521166ae9acca24ba55a81f4e64be91c04a62a7c04006ada8c4f2dabfd0c4a0a506b357e5306618146c4709",
          "sha256": "bd5ad58ffed5ca635c05c67067d42d86050b43ee3554c56248920650fc579e1a",
          "sha1": "ec32366e8fb7ff06fa36181b374be0df64b40020",
          "md5": "11bc674a9f7c8813b3d097e50bec2afe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hm-api-1.0.1+1.21.2-sources.jar",
          "url": "hm-api-1.0.1+1.21.2-sources.jar",
          "size": 36761,
          "sha512": "6b7351e332956e45c9c9c5dd75f1a9cbabe3f7eba1cc338006c18e26ad2f524d4434f86d0d59d4ad29bb478da0efd1d05067206dde5ab052eef4049f1e367c28",
          "sha256": "70036abccfed3022eb14f873c2ec1cf2d78e3b16b8de7613010181ce58036bc4",
          "sha1": "b8445f7a3356ea1062508fc1a1280c39901c2ad8",
          "md5": "8f2203213f0f9f907fcaeb12caa6a61e"
        }
      ]
    }
  ]
}
