{
  "formatVersion": "1.1",
  "component": {
    "group": "net.azureaaron",
    "module": "networth-calculator",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "8.0.16"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "networth-calculator-1.0.5.jar",
          "url": "networth-calculator-1.0.5.jar",
          "size": 84404,
          "sha512": "3fda9655f9f1aebf3fcf19b1cc8ab9228cf251b55566d6e79666a2805b4520e133040515f73dadf954e6f5a7179892298e4f51efb42772c1d2420a78e07ccdf5",
          "sha256": "e272de5b65c272f2d97c2990105c9ac1a03a8e33db2cbda351f7e72ac1cc457d",
          "sha1": "169289873662f719d2eb3864028b084e66b18f22",
          "md5": "dff99fdd59881fc577a1818be74c147e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "8.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "networth-calculator-1.0.5.jar",
          "url": "networth-calculator-1.0.5.jar",
          "size": 84404,
          "sha512": "3fda9655f9f1aebf3fcf19b1cc8ab9228cf251b55566d6e79666a2805b4520e133040515f73dadf954e6f5a7179892298e4f51efb42772c1d2420a78e07ccdf5",
          "sha256": "e272de5b65c272f2d97c2990105c9ac1a03a8e33db2cbda351f7e72ac1cc457d",
          "sha1": "169289873662f719d2eb3864028b084e66b18f22",
          "md5": "dff99fdd59881fc577a1818be74c147e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "networth-calculator-1.0.5-sources.jar",
          "url": "networth-calculator-1.0.5-sources.jar",
          "size": 31180,
          "sha512": "4704fcc9f057d63f5ee5e45a550e259526619ed6b505caf6fb9a6668ddbd8db7336a91ab3a65014d710810b2291d0a6ac78df2d9d627d8c59c156bc93d5bae18",
          "sha256": "41fce6f3586ee3831452e54049adbd7d277c1201528c008b5a89cb61f4aee405",
          "sha1": "8342db07722d6579f2e7dcacb1aecd5a5d80a091",
          "md5": "45130c42797b236767554a7d00360e80"
        }
      ]
    }
  ]
}
